// Generated by wakeword/export_model.py from models/hey_keryx_v4.pt; do not edit.
#pragma once

#define KWW_BANDS 40
#define KWW_STRIDE 3
#define KWW_FIRST_KERNEL 5
#define KWW_FIRST_FILTERS 32
#define KWW_FILTERS 64
#define KWW_BLOCKS 5
#define KWW_MAX_KERNEL 19
#define KWW_RECEPTIVE 191
#define KWW_THRESHOLD 0.950f
