"""Exports a trained wake word model to C for the ESP32, and checks the C code against PyTorch.

Writes firmware/components/keryx_wakeword/include/kww_config.h (layer shapes, threshold) and kww_weights.h
(float weights of train.py's MixedNet, each batch norm folded into the pointwise convolution before it). With --check it also builds
kww_model.c for this machine, streams test features through it frame by frame, as the ESP32 will, and compares
every output with PyTorch running the same features as one window.

    ../wakeword/.venv-train/bin/python export_model.py data/runs/hey_v4/best.pt --threshold 0.95 --check
"""

import argparse
import ctypes
import subprocess
import tempfile
from pathlib import Path

import numpy as np
import torch

import train as T

HERE = Path(__file__).resolve().parent
COMPONENT = HERE.parent / "firmware" / "components" / "keryx_wakeword"
FRONTEND = HERE.parent / "firmware" / "components" / "micro_frontend"


def floats(name, values):
    values = np.asarray(values, dtype=np.float32).ravel()
    rows = [", ".join(f"{v:.9g}f" for v in values[i : i + 8]) for i in range(0, len(values), 8)]
    return f"static const float KWW_WEIGHTS {name}[{len(values)}] = {{\n    " + ",\n    ".join(rows) + "\n};\n"


def export(model, threshold, source):
    model.eval()
    layers = list(model.body)
    first = layers[0]
    blocks = [layers[i : i + 4] for i in range(2, len(layers), 4)]  # MixConv, pointwise, BatchNorm, ReLU
    head = model.head[1]

    config = [
        f"// Generated by wakeword/export_model.py from {source}; do not edit.\n",
        "#pragma once\n\n",
        f"#define KWW_BANDS {first.in_channels}\n",
        f"#define KWW_STRIDE {T.STRIDE}\n",
        f"#define KWW_FIRST_KERNEL {T.FIRST_KERNEL}\n",
        f"#define KWW_FIRST_FILTERS {first.out_channels}\n",
        f"#define KWW_FILTERS {blocks[0][1].out_channels}\n",
        f"#define KWW_BLOCKS {len(blocks)}\n",
        f"#define KWW_MAX_KERNEL {max(max(k) for k in T.BLOCKS)}\n",
        f"#define KWW_RECEPTIVE {T.RECEPTIVE}\n",
        f"#define KWW_THRESHOLD {threshold:.3f}f\n",
    ]
    out = [
        f"// Generated by wakeword/export_model.py from {source}; do not edit. Included by kww_model.c only.\n",
        "// KWW_WEIGHTS places the arrays (kww_model.c defines it: in internal RAM on the ESP32).\n",
        "#pragma once\n\n",
        '#include "kww_config.h"\n\n',
    ]
    # first convolution: weight [out][band][tap]
    out.append(floats("kww_first_weight", first.weight.detach().numpy()))
    out.append(floats("kww_first_bias", first.bias.detach().numpy()))

    inputs, groups, channels, kernels = [], [], [], []
    for i, (mix, pointwise, bn, _) in enumerate(blocks):
        inputs.append(sum(mix.splits))
        groups.append(len(mix.convs))
        channels.append(list(mix.splits) + [0] * (2 - len(mix.splits)))
        kernels.append([c.kernel_size[0] for c in mix.convs] + [0] * (2 - len(mix.convs)))
        # depthwise: per channel, its group's taps, groups in order
        dw_w = np.concatenate([c.weight.detach().numpy()[:, 0, :].ravel() for c in mix.convs])
        dw_b = np.concatenate([c.bias.detach().numpy() for c in mix.convs])
        out.append(floats(f"kww_dw_weight_{i}", dw_w))
        out.append(floats(f"kww_dw_bias_{i}", dw_b))
        # pointwise with batch norm folded in: y = s * (W x + b - mean) + beta, s = gamma / sqrt(var + eps)
        s = (bn.weight / torch.sqrt(bn.running_var + bn.eps)).detach().numpy()
        w = pointwise.weight.detach().numpy()[:, :, 0] * s[:, None]
        b = (pointwise.bias.detach().numpy() - bn.running_mean.numpy()) * s + bn.bias.detach().numpy()
        out.append(floats(f"kww_pw_weight_{i}", w))
        out.append(floats(f"kww_pw_bias_{i}", b))

    n = len(blocks)
    table = lambda name, rows: f"static const int {name}[KWW_BLOCKS][2] = {{" + ", ".join(
        "{" + ", ".join(map(str, r)) + "}" for r in rows) + "};\n"
    out.append(f"static const int kww_block_inputs[KWW_BLOCKS] = {{{', '.join(map(str, inputs))}}};\n")
    out.append(f"static const int kww_block_groups[KWW_BLOCKS] = {{{', '.join(map(str, groups))}}};\n")
    out.append(table("kww_group_channels", channels))
    out.append(table("kww_group_kernel", kernels))
    for kind in ("dw_weight", "dw_bias", "pw_weight", "pw_bias"):
        out.append(f"static const float *const kww_{kind}[KWW_BLOCKS] = {{"
                   + ", ".join(f"kww_{kind}_{i}" for i in range(n)) + "};\n")
    out.append(floats("kww_head_weight", head.weight.detach().numpy()))
    out.append(f"static const float kww_head_bias = {head.bias.item():.9g}f;\n")
    return "".join(config), "".join(out)


def build_host_library(tmp):
    """The firmware's wake word C code (frontend and model) as a shared library for this machine."""
    lib_dir = FRONTEND / "tensorflow/lite/experimental/microfrontend/lib"
    sources = [str(p) for p in sorted(lib_dir.glob("*.cc"))]
    objects = []
    for src in sources + [str(COMPONENT / f"kww_{m}.c") for m in ("decimate", "frontend", "model")]:
        obj = Path(tmp) / (Path(src).stem + ".o")
        compiler = ["c++", "-std=c++17"] if src.endswith(".cc") else ["cc"]
        subprocess.run(compiler + ["-O2", "-fPIC", "-c", "-I", str(FRONTEND), "-I", str(FRONTEND / "kissfft"),
                                   "-I", str(COMPONENT / "include"), "-I", str(COMPONENT), src, "-o", str(obj)],
                       check=True)
        objects.append(str(obj))
    lib = Path(tmp) / "libkww.so"
    subprocess.run(["c++", "-shared", *objects, "-o", str(lib)], check=True)
    return ctypes.CDLL(str(lib))


def c_features(c, audio):
    """micro_speech features of 16-bit audio through the C frontend."""
    frontend = ctypes.create_string_buffer(1 << 16)  # larger than kww_frontend_t
    assert c.kww_frontend_init(frontend)
    pcm = np.ascontiguousarray(audio, dtype=np.int16)
    frames = np.zeros((len(pcm) // 160 + 1, 40), dtype=np.float32)
    n = c.kww_frontend_process(frontend, pcm.ctypes.data_as(ctypes.c_void_p), ctypes.c_size_t(len(pcm)),
                               frames.ctypes.data_as(ctypes.c_void_p), len(frames))
    return frames[:n]


def check_frontend(c):
    """Compares the C frontend with pymicro-features on a few recordings; returns the worst difference."""
    import build_dataset as B
    worst, n = 0.0, 0
    for label in ("hey-me", "neg-room"):
        for p in sorted((HERE / "data" / "recordings" / label).glob("*.wav"))[:5]:
            audio = (B.load(p) * 32768).clip(-32768, 32767).astype(np.int16)
            want = B.features(audio.astype(np.float32) / 32768)
            got = c_features(c, audio)
            k = min(len(want), len(got))
            worst, n = max(worst, float(np.abs(got[:k] - want[:k]).max())), n + 1
    return worst, n


def check_pipeline(c, model, n_takes=8):
    """The whole device chain on raw 48 kHz board recordings (decimation, frontend, streaming model in C) against
    the training chain (resample_poly, pymicro-features, PyTorch): worst difference of each take's peak score."""
    import wave
    from scipy.signal import resample_poly
    import build_dataset as B
    model.eval()
    worst, peaks = 0.0, []
    for p in sorted((HERE / "data" / "recordings" / "hey-me" / "raw").glob("*.wav"))[:n_takes]:
        with wave.open(str(p)) as w:
            asr = np.frombuffer(w.readframes(w.getnframes()), "<i2").reshape(-1, 2)[:, 1]
        asr = np.concatenate([np.zeros(48000 * 3 // 2, np.int16), asr])  # takes are shorter than the model's view
        # training chain: what record.py and build_dataset.py did
        ref16 = resample_poly(asr.astype(np.float64), 1, 3)
        with torch.no_grad():
            want = float(torch.sigmoid(model(torch.from_numpy(B.features(ref16 / 32768))[None])[0]).max())
        # device chain
        dec = ctypes.create_string_buffer(1 << 12)
        c.kww_decimate_reset(dec)
        out16 = np.zeros(len(asr) // 3 + 2, dtype=np.int16)
        n = c.kww_decimate(dec, asr.ctypes.data_as(ctypes.c_void_p), ctypes.c_size_t(len(asr)),
                           out16.ctypes.data_as(ctypes.c_void_p))
        feats = c_features(c, out16[:n])
        state, prob, got = ctypes.create_string_buffer(1 << 20), ctypes.c_float(), 0.0
        c.kww_reset(state)
        for frame in np.ascontiguousarray(feats, dtype=np.float32):
            if c.kww_push(state, frame.ctypes.data_as(ctypes.POINTER(ctypes.c_float)), ctypes.byref(prob)):
                got = max(got, prob.value)
        worst = max(worst, abs(got - want))
        peaks.append((round(want, 3), round(got, 3)))
    return worst, peaks


def check(model, c, n_streams=6):
    """Streams test features through the C model and compares with PyTorch; returns the worst difference."""
    if True:
        state = ctypes.create_string_buffer(1 << 20)  # larger than kww_state_t
        c.kww_push.restype = ctypes.c_bool
        prob = ctypes.c_float()

        x, _ = T.load_set("test_user_pos")
        streams = [x[i].float().numpy() for i in range(n_streams)]
        streams.append(np.load(T.FEAT / "test_home.npz")["home"].astype(np.float32)[:3000])
        worst = 0.0
        model.eval()
        for f in streams:
            c.kww_reset(state)
            got = []
            for frame in np.ascontiguousarray(f, dtype=np.float32):
                if c.kww_push(state, frame.ctypes.data_as(ctypes.POINTER(ctypes.c_float)), ctypes.byref(prob)):
                    got.append(prob.value)
            with torch.no_grad():
                want = torch.sigmoid(model(torch.from_numpy(f)[None])[0]).numpy()
            # C emits an output from the first full kernel on; PyTorch only once the whole field is filled
            got = np.array(got)[-len(want):]
            worst = max(worst, float(np.abs(got - want).max()))
        return worst, len(streams)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("model", type=Path)
    parser.add_argument("--threshold", type=float, default=0.95)
    parser.add_argument("--check", action="store_true", help="compare the C code with PyTorch")
    args = parser.parse_args()

    model = T.MixedNet()
    model.load_state_dict(torch.load(args.model, map_location="cpu"))
    config, weights = export(model, args.threshold, args.model.resolve().relative_to(HERE))
    (COMPONENT / "include" / "kww_config.h").write_text(config)
    (COMPONENT / "kww_weights.h").write_text(weights)
    print(f"wrote kww_config.h and kww_weights.h ({len(weights) // 1024} KB source) into {COMPONENT}")
    if args.check:
        with tempfile.TemporaryDirectory() as tmp:
            c = build_host_library(tmp)
            worst, n = check_frontend(c)
            print(f"C frontend vs pymicro-features over {n} recordings: max |difference| {worst:.2e}")
            worst, n = check(model, c)
            print(f"C model vs PyTorch over {n} streams: max |difference| {worst:.2e}")
            c.kww_push.restype = ctypes.c_bool
            c.kww_decimate.restype = ctypes.c_size_t
            worst, peaks = check_pipeline(c, model)
            print(f"device chain vs training chain on raw board takes: peak scores (training, device) {peaks}; "
                  f"max |difference| {worst:.3f}")


if __name__ == "__main__":
    main()
